--------------------------------------------------------
--  Fichier cr�� - samedi-avril-25-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADDRESSES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ADDRESSES" 
   (	"ID" NUMBER(19,0), 
	"LABEL" VARCHAR2(120 BYTE), 
	"STREET_LINE" VARCHAR2(255 BYTE), 
	"CITY" VARCHAR2(120 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"GOUVERNORAT" VARCHAR2(120 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMINS_ASSOCIATION
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ADMINS_ASSOCIATION" 
   (	"ID_ADMIN_ASSOCIATION" NUMBER(19,0), 
	"ORGANIZATION_ID" NUMBER(19,0), 
	"NOM_ASSOCIATION" VARCHAR2(180 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANNONCES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ANNONCES" 
   (	"ID_ANNONCE" NUMBER(19,0), 
	"TITRE" VARCHAR2(180 BYTE), 
	"DESCRIPTION" CLOB, 
	"TYPE_ALIMENT" VARCHAR2(120 BYTE), 
	"PRIX" NUMBER(10,2) DEFAULT 0, 
	"QUANTITE" NUMBER(10,0), 
	"UNITE" VARCHAR2(50 BYTE), 
	"LOCALISATION" VARCHAR2(190 BYTE), 
	"STATUT" VARCHAR2(30 BYTE), 
	"PUBLIC_VISIBILITY_AT" TIMESTAMP (6), 
	"PICKUP_START" TIMESTAMP (6), 
	"PICKUP_END" TIMESTAMP (6), 
	"DATE_EXPIRATION" TIMESTAMP (6), 
	"CATEGORIE_ID" NUMBER(19,0), 
	"ZONE_ID" NUMBER(19,0), 
	"PROPRIETAIRE_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ASSOCIATION_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" 
   (	"ID" NUMBER(19,0), 
	"ORGANIZATION_ID" NUMBER(19,0), 
	"ADDRESS_ID" NUMBER(19,0), 
	"IS_PRIMARY" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."CATEGORIES" 
   (	"ID_CAT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONSULTATIONS_ANNONCES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" 
   (	"ID_CONSULTATION" NUMBER(19,0), 
	"UTILISATEUR_ID" NUMBER(19,0), 
	"ANNONCE_ID" NUMBER(19,0), 
	"DATE_CONSULTATION" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTACT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."CONTACT_MESSAGES" 
   (	"ID" NUMBER(19,0), 
	"FULLNAME" VARCHAR2(180 BYTE), 
	"EMAIL" VARCHAR2(190 BYTE), 
	"ORGANIZATION" VARCHAR2(180 BYTE), 
	"ROLE_LABEL" VARCHAR2(100 BYTE), 
	"MESSAGE" CLOB, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MESSAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DISTRIBUTIONS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."DISTRIBUTIONS" 
   (	"ID_DISTRIBUTION" NUMBER(19,0), 
	"RESERVATION_ID" NUMBER(19,0), 
	"ADMIN_ASSOCIATION_ID" NUMBER(19,0), 
	"QUANTITE_DISTRIB" NUMBER(10,0), 
	"DATE_DISTRIB" TIMESTAMP (6), 
	"STATUT" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."NOTIFICATIONS" 
   (	"ID_NOTIFICATION" NUMBER(19,0), 
	"UTILISATEUR_ID" NUMBER(19,0), 
	"ADMIN_ASSOCIATION_ID" NUMBER(19,0), 
	"PROPRIETAIRE_ID" NUMBER(19,0), 
	"ANNONCE_ID" NUMBER(19,0), 
	"RESERVATION_ID" NUMBER(19,0), 
	"REPORT_ID" NUMBER(19,0), 
	"MESSAGE_NOTIFICATION" CLOB, 
	"TYPE" VARCHAR2(30 BYTE), 
	"CHANNEL" VARCHAR2(10 BYTE), 
	"SENT_AT" TIMESTAMP (6), 
	"READ_AT" TIMESTAMP (6), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("MESSAGE_NOTIFICATION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ORGANIZATIONS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ORGANIZATIONS" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(180 BYTE), 
	"ORGANIZATION_TYPE" VARCHAR2(100 BYTE) DEFAULT 'association', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAIEMENTS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."PAIEMENTS" 
   (	"ID_PAIEMENT" NUMBER(19,0), 
	"RESERVATION_ID" NUMBER(19,0), 
	"MONTANT" NUMBER(10,2), 
	"METHODE_PAIEMENT" VARCHAR2(20 BYTE), 
	"DATE_PAIEMENT" TIMESTAMP (6), 
	"STATUT" VARCHAR2(20 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PICKUPS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."PICKUPS" 
   (	"ID" NUMBER(19,0), 
	"RESERVATION_ID" NUMBER(19,0), 
	"SCHEDULED_AT" TIMESTAMP (6), 
	"PICKED_UP_AT" TIMESTAMP (6), 
	"RECEIVER_NAME" VARCHAR2(150 BYTE), 
	"RECEIVER_PHONE" VARCHAR2(30 BYTE), 
	"PICKUP_CODE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'scheduled', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPRIETAIRES_COMMERCE
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."PROPRIETAIRES_COMMERCE" 
   (	"ID_COMMERCE" NUMBER(19,0), 
	"NOM_COMMERCE" VARCHAR2(120 BYTE), 
	"TYPE_COMMERCE" VARCHAR2(120 BYTE), 
	"BUSINESS_LICENCE" VARCHAR2(120 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECUS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."RECUS" 
   (	"ID_RECU" NUMBER(19,0), 
	"PAIEMENT_ID" NUMBER(19,0), 
	"MONTANT" NUMBER(10,2), 
	"DATE_EMISSION" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORT_CONSULTATIONS_COMMERCE
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" 
   (	"ID" NUMBER(19,0), 
	"REPORT_ID" NUMBER(19,0), 
	"PROPRIETAIRE_ID" NUMBER(19,0), 
	"CONSULTED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORT_CONSULT_SUPER_ADMIN
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" 
   (	"ID" NUMBER(19,0), 
	"REPORT_ID" NUMBER(19,0), 
	"SUPER_ADMIN_ID" NUMBER(19,0), 
	"CONSULTED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."REPORTS" 
   (	"ID" NUMBER(19,0), 
	"GENERATED_BY" NUMBER(19,0), 
	"REPORT_TYPE" VARCHAR2(20 BYTE), 
	"PERIOD_START" DATE, 
	"PERIOD_END" DATE, 
	"TOTAL_FOOD_SAVED_KG" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_RESERVATIONS" NUMBER(10,0) DEFAULT 0, 
	"TOTAL_DISTRIBUTIONS" NUMBER(10,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION_DISTRIBUTIONS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" 
   (	"RESERVATION_ID" NUMBER(19,0), 
	"DISTRIBUTION_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."RESERVATIONS" 
   (	"ID_RESERVATION" NUMBER(19,0), 
	"ANNONCE_ID" NUMBER(19,0), 
	"UTILISATEUR_ID" NUMBER(19,0), 
	"ADMIN_ASSOCIATION_ID" NUMBER(19,0), 
	"QUANTITE_RESERVEE" NUMBER(10,0), 
	"STATUT" VARCHAR2(30 BYTE), 
	"DATE_RESERVATION" TIMESTAMP (6), 
	"DATE_PICKUP" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ROLES" 
   (	"ID_ROLE" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUGGESTIONS_IA
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."SUGGESTIONS_IA" 
   (	"ID" NUMBER(19,0), 
	"FOOD_ITEM_ID" NUMBER(19,0), 
	"RISK_LEVEL" VARCHAR2(20 BYTE), 
	"EXP_PROB" NUMBER(5,2), 
	"ACTION" CLOB, 
	"GEN_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ACTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUPER_ADMINS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."SUPER_ADMINS" 
   (	"ID_SUPER_ADMIN" NUMBER(19,0), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE), 
	"ADMIN_LEVEL" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" 
   (	"UTILISATEUR_ID" NUMBER(19,0), 
	"CATEGORIE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEURS
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."UTILISATEURS" 
   (	"ID_UTIL" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0), 
	"PRENOM" VARCHAR2(120 BYTE), 
	"NOM" VARCHAR2(120 BYTE), 
	"EMAIL" VARCHAR2(190 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE), 
	"NUM_TEL" VARCHAR2(30 BYTE), 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR_ZONES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."UTILISATEUR_ZONES" 
   (	"UTILISATEUR_ID" NUMBER(19,0), 
	"ZONE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ZONES_GEOGRAPHIQUES
--------------------------------------------------------

  CREATE TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" 
   (	"ID_ZONE" NUMBER(19,0), 
	"NOM" VARCHAR2(100 BYTE), 
	"CODE_POSTAL" NUMBER(10,0), 
	"VILLE_NOM" VARCHAR2(120 BYTE), 
	"GOUVERNORAT" VARCHAR2(120 BYTE), 
	"USER_ID" NUMBER(19,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FOODLOOP.ADDRESSES
SET DEFINE OFF;
Insert into FOODLOOP.ADDRESSES (ID,LABEL,STREET_LINE,CITY,POSTAL_CODE,GOUVERNORAT,CREATED_AT) values ('1','Siege Tunis','14 Rue de Palestine','Tunis','1002','Tunis',to_timestamp('20/04/26 08:35:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ADDRESSES (ID,LABEL,STREET_LINE,CITY,POSTAL_CODE,GOUVERNORAT,CREATED_AT) values ('2','Depot La Marsa','22 Avenue Taieb Mhiri','La Marsa','2070','Tunis',to_timestamp('20/04/26 08:36:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ADDRESSES (ID,LABEL,STREET_LINE,CITY,POSTAL_CODE,GOUVERNORAT,CREATED_AT) values ('3','Hub Sfax','5 Rue de la Republique','Sfax','3000','Sfax',to_timestamp('20/04/26 08:37:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.ADMINS_ASSOCIATION
SET DEFINE OFF;
Insert into FOODLOOP.ADMINS_ASSOCIATION (ID_ADMIN_ASSOCIATION,ORGANIZATION_ID,NOM_ASSOCIATION,CREATED_AT) values ('1','1','Association Nour',to_timestamp('20/04/26 08:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ADMINS_ASSOCIATION (ID_ADMIN_ASSOCIATION,ORGANIZATION_ID,NOM_ASSOCIATION,CREATED_AT) values ('2','2','Banque Alimentaire Sfax',to_timestamp('20/04/26 08:42:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.ANNONCES
SET DEFINE OFF;
Insert into FOODLOOP.ANNONCES (ID_ANNONCE,TITRE,TYPE_ALIMENT,PRIX,QUANTITE,UNITE,LOCALISATION,STATUT,PUBLIC_VISIBILITY_AT,PICKUP_START,PICKUP_END,DATE_EXPIRATION,CATEGORIE_ID,ZONE_ID,PROPRIETAIRE_ID,CREATED_AT,UPDATED_AT) values ('1','Sandwichs invendus du matin','Boulangerie','2.90','35','pieces','Rue de Rome','priority_access',to_timestamp('20/04/26 15:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 15:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 16:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 18:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'1','1','1',to_timestamp('20/04/26 14:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 14:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ANNONCES (ID_ANNONCE,TITRE,TYPE_ALIMENT,PRIX,QUANTITE,UNITE,LOCALISATION,STATUT,PUBLIC_VISIBILITY_AT,PICKUP_START,PICKUP_END,DATE_EXPIRATION,CATEGORIE_ID,ZONE_ID,PROPRIETAIRE_ID,CREATED_AT,UPDATED_AT) values ('2','Couscous vegetal midi','Plat cuisine','4.60','18','barquettes','La Marsa Plage','available',to_timestamp('20/04/26 11:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 18:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 19:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 21:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'2','2','2',to_timestamp('20/04/26 10:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 12:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ANNONCES (ID_ANNONCE,TITRE,TYPE_ALIMENT,PRIX,QUANTITE,UNITE,LOCALISATION,STATUT,PUBLIC_VISIBILITY_AT,PICKUP_START,PICKUP_END,DATE_EXPIRATION,CATEGORIE_ID,ZONE_ID,PROPRIETAIRE_ID,CREATED_AT,UPDATED_AT) values ('3','Paniers fruits et laitages','Epicerie','3.40','24','packs','Sfax Medina','reserved',to_timestamp('20/04/26 10:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 15:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 16:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 19:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'3','3','3',to_timestamp('20/04/26 09:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ANNONCES (ID_ANNONCE,TITRE,TYPE_ALIMENT,PRIX,QUANTITE,UNITE,LOCALISATION,STATUT,PUBLIC_VISIBILITY_AT,PICKUP_START,PICKUP_END,DATE_EXPIRATION,CATEGORIE_ID,ZONE_ID,PROPRIETAIRE_ID,CREATED_AT,UPDATED_AT) values ('4','Salades pretes a recuperer','Repas frais','2.30','12','box','Sousse Corniche','available',to_timestamp('20/04/26 12:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 17:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 18:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 20:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'2','4','2',to_timestamp('20/04/26 11:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 11:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ANNONCES (ID_ANNONCE,TITRE,TYPE_ALIMENT,PRIX,QUANTITE,UNITE,LOCALISATION,STATUT,PUBLIC_VISIBILITY_AT,PICKUP_START,PICKUP_END,DATE_EXPIRATION,CATEGORIE_ID,ZONE_ID,PROPRIETAIRE_ID,CREATED_AT,UPDATED_AT) values ('5','Yaourts proches de date','Produits laitiers','1.80','20','pots','Bab Bhar','picked_up',to_timestamp('20/04/26 08:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'4','1','3',to_timestamp('20/04/26 07:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.ASSOCIATION_ADDRESSES
SET DEFINE OFF;
Insert into FOODLOOP.ASSOCIATION_ADDRESSES (ID,ORGANIZATION_ID,ADDRESS_ID,IS_PRIMARY) values ('1','1','1','1');
Insert into FOODLOOP.ASSOCIATION_ADDRESSES (ID,ORGANIZATION_ID,ADDRESS_ID,IS_PRIMARY) values ('2','1','2','0');
Insert into FOODLOOP.ASSOCIATION_ADDRESSES (ID,ORGANIZATION_ID,ADDRESS_ID,IS_PRIMARY) values ('3','2','3','1');
REM INSERTING into FOODLOOP.CATEGORIES
SET DEFINE OFF;
Insert into FOODLOOP.CATEGORIES (ID_CAT,NOM) values ('1','Boulangerie');
Insert into FOODLOOP.CATEGORIES (ID_CAT,NOM) values ('2','Plats cuisines');
Insert into FOODLOOP.CATEGORIES (ID_CAT,NOM) values ('3','Epicerie fraiche');
Insert into FOODLOOP.CATEGORIES (ID_CAT,NOM) values ('4','Produits laitiers');
REM INSERTING into FOODLOOP.CONSULTATIONS_ANNONCES
SET DEFINE OFF;
Insert into FOODLOOP.CONSULTATIONS_ANNONCES (ID_CONSULTATION,UTILISATEUR_ID,ANNONCE_ID,DATE_CONSULTATION) values ('1','1','2',to_timestamp('20/04/26 12:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.CONSULTATIONS_ANNONCES (ID_CONSULTATION,UTILISATEUR_ID,ANNONCE_ID,DATE_CONSULTATION) values ('2','1','4',to_timestamp('20/04/26 12:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.CONSULTATIONS_ANNONCES (ID_CONSULTATION,UTILISATEUR_ID,ANNONCE_ID,DATE_CONSULTATION) values ('3','2','3',to_timestamp('20/04/26 13:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.CONSULTATIONS_ANNONCES (ID_CONSULTATION,UTILISATEUR_ID,ANNONCE_ID,DATE_CONSULTATION) values ('4','2','5',to_timestamp('20/04/26 13:25:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.CONTACT_MESSAGES
SET DEFINE OFF;
Insert into FOODLOOP.CONTACT_MESSAGES (ID,FULLNAME,EMAIL,ORGANIZATION,ROLE_LABEL,CREATED_AT) values ('1','Meriem Hadded','meriem@example.com','Collectif Zero Gaspillage','benevole',to_timestamp('20/04/26 10:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.CONTACT_MESSAGES (ID,FULLNAME,EMAIL,ORGANIZATION,ROLE_LABEL,CREATED_AT) values ('2','Nabil Gharbi','nabil@example.com','Epicerie du Lac','commercant',to_timestamp('20/04/26 11:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.DISTRIBUTIONS
SET DEFINE OFF;
Insert into FOODLOOP.DISTRIBUTIONS (ID_DISTRIBUTION,RESERVATION_ID,ADMIN_ASSOCIATION_ID,QUANTITE_DISTRIB,DATE_DISTRIB,STATUT,CREATED_AT) values ('1','2','1','20',to_timestamp('20/04/26 16:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'completed',to_timestamp('20/04/26 14:25:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.DISTRIBUTIONS (ID_DISTRIBUTION,RESERVATION_ID,ADMIN_ASSOCIATION_ID,QUANTITE_DISTRIB,DATE_DISTRIB,STATUT,CREATED_AT) values ('2','4','2','12',to_timestamp('20/04/26 16:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'in_progress',to_timestamp('20/04/26 13:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.NOTIFICATIONS
SET DEFINE OFF;
Insert into FOODLOOP.NOTIFICATIONS (ID_NOTIFICATION,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,PROPRIETAIRE_ID,ANNONCE_ID,RESERVATION_ID,REPORT_ID,TYPE,CHANNEL,SENT_AT,READ_AT,STATUS,CREATED_AT) values ('1','1',null,null,'2','1',null,'reservation_update','web',to_timestamp('20/04/26 12:55:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:02:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'read',to_timestamp('20/04/26 12:55:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.NOTIFICATIONS (ID_NOTIFICATION,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,PROPRIETAIRE_ID,ANNONCE_ID,RESERVATION_ID,REPORT_ID,TYPE,CHANNEL,SENT_AT,READ_AT,STATUS,CREATED_AT) values ('2',null,'1',null,'1','2',null,'new_listing','email',to_timestamp('20/04/26 14:12:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'queued',to_timestamp('20/04/26 14:12:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.NOTIFICATIONS (ID_NOTIFICATION,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,PROPRIETAIRE_ID,ANNONCE_ID,RESERVATION_ID,REPORT_ID,TYPE,CHANNEL,SENT_AT,READ_AT,STATUS,CREATED_AT) values ('3',null,null,'2','4','3',null,'pickup_reminder','web',to_timestamp('20/04/26 17:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'queued',to_timestamp('20/04/26 17:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.NOTIFICATIONS (ID_NOTIFICATION,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,PROPRIETAIRE_ID,ANNONCE_ID,RESERVATION_ID,REPORT_ID,TYPE,CHANNEL,SENT_AT,READ_AT,STATUS,CREATED_AT) values ('4',null,'2',null,'3','4',null,'expiration_alert','sms',to_timestamp('20/04/26 15:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'queued',to_timestamp('20/04/26 15:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.NOTIFICATIONS (ID_NOTIFICATION,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,PROPRIETAIRE_ID,ANNONCE_ID,RESERVATION_ID,REPORT_ID,TYPE,CHANNEL,SENT_AT,READ_AT,STATUS,CREATED_AT) values ('5',null,null,'1',null,null,'1','report_ready','email',to_timestamp('20/04/26 18:31:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'queued',to_timestamp('20/04/26 18:31:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.ORGANIZATIONS
SET DEFINE OFF;
Insert into FOODLOOP.ORGANIZATIONS (ID,NAME,ORGANIZATION_TYPE,CREATED_AT) values ('1','Association Nour','association',to_timestamp('20/04/26 08:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ORGANIZATIONS (ID,NAME,ORGANIZATION_TYPE,CREATED_AT) values ('2','Banque Alimentaire Sfax','association',to_timestamp('20/04/26 08:32:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.PAIEMENTS
SET DEFINE OFF;
Insert into FOODLOOP.PAIEMENTS (ID_PAIEMENT,RESERVATION_ID,MONTANT,METHODE_PAIEMENT,DATE_PAIEMENT,STATUT,CREATED_AT) values ('1','1','12,5','par carte',to_timestamp('20/04/26 12:52:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'confirme',to_timestamp('20/04/26 12:52:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PAIEMENTS (ID_PAIEMENT,RESERVATION_ID,MONTANT,METHODE_PAIEMENT,DATE_PAIEMENT,STATUT,CREATED_AT) values ('2','3','5','espece',to_timestamp('20/04/26 13:08:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'confirme',to_timestamp('20/04/26 13:08:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.PICKUPS
SET DEFINE OFF;
Insert into FOODLOOP.PICKUPS (ID,RESERVATION_ID,SCHEDULED_AT,PICKED_UP_AT,RECEIVER_NAME,RECEIVER_PHONE,PICKUP_CODE,STATUS,CREATED_AT) values ('1','1',to_timestamp('20/04/26 18:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 18:24:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Amal Ben Ali','22123456','PU-AML-001','done',to_timestamp('20/04/26 12:55:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PICKUPS (ID,RESERVATION_ID,SCHEDULED_AT,PICKED_UP_AT,RECEIVER_NAME,RECEIVER_PHONE,PICKUP_CODE,STATUS,CREATED_AT) values ('2','2',to_timestamp('20/04/26 15:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Equipe Nour','70001010','PU-NOUR-002','scheduled',to_timestamp('20/04/26 14:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PICKUPS (ID,RESERVATION_ID,SCHEDULED_AT,PICKED_UP_AT,RECEIVER_NAME,RECEIVER_PHONE,PICKUP_CODE,STATUS,CREATED_AT) values ('3','3',to_timestamp('20/04/26 17:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 17:42:00,000000000','DD/MM/RR HH24:MI:SS,FF'),'Sami Trabelsi','55123456','PU-SAM-003','done',to_timestamp('20/04/26 13:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PICKUPS (ID,RESERVATION_ID,SCHEDULED_AT,PICKED_UP_AT,RECEIVER_NAME,RECEIVER_PHONE,PICKUP_CODE,STATUS,CREATED_AT) values ('4','4',to_timestamp('20/04/26 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Equipe Sfax','74444000','PU-SFAX-004','in_progress',to_timestamp('20/04/26 13:35:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.PROPRIETAIRES_COMMERCE
SET DEFINE OFF;
Insert into FOODLOOP.PROPRIETAIRES_COMMERCE (ID_COMMERCE,NOM_COMMERCE,TYPE_COMMERCE,BUSINESS_LICENCE,CREATED_AT) values ('1','Boulangerie El Medina','Boulangerie','LIC-BEM-2026',to_timestamp('20/04/26 08:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PROPRIETAIRES_COMMERCE (ID_COMMERCE,NOM_COMMERCE,TYPE_COMMERCE,BUSINESS_LICENCE,CREATED_AT) values ('2','Carthage Kitchen','Restaurant','LIC-CK-2026',to_timestamp('20/04/26 08:47:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.PROPRIETAIRES_COMMERCE (ID_COMMERCE,NOM_COMMERCE,TYPE_COMMERCE,BUSINESS_LICENCE,CREATED_AT) values ('3','Green Basket Market','Supermarche',null,to_timestamp('20/04/26 08:49:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.RECUS
SET DEFINE OFF;
Insert into FOODLOOP.RECUS (ID_RECU,PAIEMENT_ID,MONTANT,DATE_EMISSION,CREATED_AT) values ('1','1','12,5',to_timestamp('20/04/26 12:53:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 12:53:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.RECUS (ID_RECU,PAIEMENT_ID,MONTANT,DATE_EMISSION,CREATED_AT) values ('2','2','5',to_timestamp('20/04/26 13:09:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:09:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.REPORT_CONSULTATIONS_COMMERCE
SET DEFINE OFF;
Insert into FOODLOOP.REPORT_CONSULTATIONS_COMMERCE (ID,REPORT_ID,PROPRIETAIRE_ID,CONSULTED_AT) values ('1','1','1',to_timestamp('20/04/26 18:35:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.REPORT_CONSULTATIONS_COMMERCE (ID,REPORT_ID,PROPRIETAIRE_ID,CONSULTED_AT) values ('2','1','2',to_timestamp('20/04/26 18:36:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.REPORT_CONSULTATIONS_COMMERCE (ID,REPORT_ID,PROPRIETAIRE_ID,CONSULTED_AT) values ('3','2','3',to_timestamp('20/04/26 18:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.REPORT_CONSULT_SUPER_ADMIN
SET DEFINE OFF;
Insert into FOODLOOP.REPORT_CONSULT_SUPER_ADMIN (ID,REPORT_ID,SUPER_ADMIN_ID,CONSULTED_AT) values ('1','1','1',to_timestamp('20/04/26 18:33:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.REPORT_CONSULT_SUPER_ADMIN (ID,REPORT_ID,SUPER_ADMIN_ID,CONSULTED_AT) values ('2','2','1',to_timestamp('20/04/26 18:43:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.REPORTS
SET DEFINE OFF;
Insert into FOODLOOP.REPORTS (ID,GENERATED_BY,REPORT_TYPE,PERIOD_START,PERIOD_END,TOTAL_FOOD_SAVED_KG,TOTAL_RESERVATIONS,TOTAL_DISTRIBUTIONS,CREATED_AT) values ('1','1','daily',to_date('20/04/26','DD/MM/RR'),to_date('20/04/26','DD/MM/RR'),'148,5','4','2',to_timestamp('20/04/26 18:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.REPORTS (ID,GENERATED_BY,REPORT_TYPE,PERIOD_START,PERIOD_END,TOTAL_FOOD_SAVED_KG,TOTAL_RESERVATIONS,TOTAL_DISTRIBUTIONS,CREATED_AT) values ('2','1','weekly',to_date('14/04/26','DD/MM/RR'),to_date('20/04/26','DD/MM/RR'),'612,8','18','11',to_timestamp('20/04/26 18:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.RESERVATION_DISTRIBUTIONS
SET DEFINE OFF;
Insert into FOODLOOP.RESERVATION_DISTRIBUTIONS (RESERVATION_ID,DISTRIBUTION_ID) values ('2','1');
Insert into FOODLOOP.RESERVATION_DISTRIBUTIONS (RESERVATION_ID,DISTRIBUTION_ID) values ('4','2');
REM INSERTING into FOODLOOP.RESERVATIONS
SET DEFINE OFF;
Insert into FOODLOOP.RESERVATIONS (ID_RESERVATION,ANNONCE_ID,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,QUANTITE_RESERVEE,STATUT,DATE_RESERVATION,DATE_PICKUP,CREATED_AT) values ('1','2','1',null,'2','completed',to_timestamp('20/04/26 12:50:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 18:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 12:50:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.RESERVATIONS (ID_RESERVATION,ANNONCE_ID,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,QUANTITE_RESERVEE,STATUT,DATE_RESERVATION,DATE_PICKUP,CREATED_AT) values ('2','1',null,'1','20','approved',to_timestamp('20/04/26 14:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 15:45:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 14:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.RESERVATIONS (ID_RESERVATION,ANNONCE_ID,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,QUANTITE_RESERVEE,STATUT,DATE_RESERVATION,DATE_PICKUP,CREATED_AT) values ('3','4','2',null,'1','picked_up',to_timestamp('20/04/26 13:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 17:40:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:05:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.RESERVATIONS (ID_RESERVATION,ANNONCE_ID,UTILISATEUR_ID,ADMIN_ASSOCIATION_ID,QUANTITE_RESERVEE,STATUT,DATE_RESERVATION,DATE_PICKUP,CREATED_AT) values ('4','3',null,'2','12','approved',to_timestamp('20/04/26 13:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 13:30:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.ROLES
SET DEFINE OFF;
Insert into FOODLOOP.ROLES (ID_ROLE,NOM,CODE,CREATED_AT) values ('1','Utilisateur','citizen',to_timestamp('20/04/26 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ROLES (ID_ROLE,NOM,CODE,CREATED_AT) values ('2','ProprietaireCommerce','business_owner',to_timestamp('20/04/26 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ROLES (ID_ROLE,NOM,CODE,CREATED_AT) values ('3','AdminAssociation','association_admin',to_timestamp('20/04/26 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ROLES (ID_ROLE,NOM,CODE,CREATED_AT) values ('4','SuperAdmin','super_admin',to_timestamp('20/04/26 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.SUGGESTIONS_IA
SET DEFINE OFF;
Insert into FOODLOOP.SUGGESTIONS_IA (ID,FOOD_ITEM_ID,RISK_LEVEL,EXP_PROB,GEN_AT,CREATED_AT) values ('1','1','high','91,5',to_timestamp('20/04/26 14:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 14:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.SUGGESTIONS_IA (ID,FOOD_ITEM_ID,RISK_LEVEL,EXP_PROB,GEN_AT,CREATED_AT) values ('2','2','medium','54,25',to_timestamp('20/04/26 12:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 12:15:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.SUPER_ADMINS
SET DEFINE OFF;
Insert into FOODLOOP.SUPER_ADMINS (ID_SUPER_ADMIN,MOT_DE_PASSE,ADMIN_LEVEL,CREATED_AT) values ('1','hash-demo-super-admin','global',to_timestamp('20/04/26 08:50:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.UTILISATEUR_CATEGORIES
SET DEFINE OFF;
Insert into FOODLOOP.UTILISATEUR_CATEGORIES (UTILISATEUR_ID,CATEGORIE_ID) values ('1','2');
Insert into FOODLOOP.UTILISATEUR_CATEGORIES (UTILISATEUR_ID,CATEGORIE_ID) values ('1','4');
Insert into FOODLOOP.UTILISATEUR_CATEGORIES (UTILISATEUR_ID,CATEGORIE_ID) values ('2','1');
Insert into FOODLOOP.UTILISATEUR_CATEGORIES (UTILISATEUR_ID,CATEGORIE_ID) values ('2','3');
REM INSERTING into FOODLOOP.UTILISATEURS
SET DEFINE OFF;
Insert into FOODLOOP.UTILISATEURS (ID_UTIL,ROLE_ID,PRENOM,NOM,EMAIL,MOT_DE_PASSE,NUM_TEL,ADRESSE,CREATED_AT,UPDATED_AT) values ('1','1','Amal','Ben Ali','amal@foodloop.test','hash-demo-utilisateur-1','22123456','12 Rue de Marseille, Tunis',to_timestamp('20/04/26 08:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 08:10:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.UTILISATEURS (ID_UTIL,ROLE_ID,PRENOM,NOM,EMAIL,MOT_DE_PASSE,NUM_TEL,ADRESSE,CREATED_AT,UPDATED_AT) values ('2','1','Sami','Trabelsi','sami@foodloop.test','hash-demo-utilisateur-2','55123456','8 Avenue Habib Bourguiba, Sfax',to_timestamp('20/04/26 08:12:00,000000000','DD/MM/RR HH24:MI:SS,FF'),to_timestamp('20/04/26 08:12:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
REM INSERTING into FOODLOOP.UTILISATEUR_ZONES
SET DEFINE OFF;
Insert into FOODLOOP.UTILISATEUR_ZONES (UTILISATEUR_ID,ZONE_ID) values ('1','1');
Insert into FOODLOOP.UTILISATEUR_ZONES (UTILISATEUR_ID,ZONE_ID) values ('1','2');
Insert into FOODLOOP.UTILISATEUR_ZONES (UTILISATEUR_ID,ZONE_ID) values ('2','3');
Insert into FOODLOOP.UTILISATEUR_ZONES (UTILISATEUR_ID,ZONE_ID) values ('2','4');
REM INSERTING into FOODLOOP.ZONES_GEOGRAPHIQUES
SET DEFINE OFF;
Insert into FOODLOOP.ZONES_GEOGRAPHIQUES (ID_ZONE,NOM,CODE_POSTAL,VILLE_NOM,GOUVERNORAT,USER_ID,CREATED_AT) values ('1','Tunis Centre','1000','Tunis','Tunis','1',to_timestamp('20/04/26 08:20:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ZONES_GEOGRAPHIQUES (ID_ZONE,NOM,CODE_POSTAL,VILLE_NOM,GOUVERNORAT,USER_ID,CREATED_AT) values ('2','La Marsa','2070','La Marsa','Tunis','1',to_timestamp('20/04/26 08:22:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ZONES_GEOGRAPHIQUES (ID_ZONE,NOM,CODE_POSTAL,VILLE_NOM,GOUVERNORAT,USER_ID,CREATED_AT) values ('3','Sfax Medina','3000','Sfax','Sfax','2',to_timestamp('20/04/26 08:24:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
Insert into FOODLOOP.ZONES_GEOGRAPHIQUES (ID_ZONE,NOM,CODE_POSTAL,VILLE_NOM,GOUVERNORAT,USER_ID,CREATED_AT) values ('4','Sousse Ville','4000','Sousse','Sousse',null,to_timestamp('20/04/26 08:26:00,000000000','DD/MM/RR HH24:MI:SS,FF'));
--------------------------------------------------------
--  DDL for Index UQ_CATEGORIES_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_CATEGORIES_NOM" ON "FOODLOOP"."CATEGORIES" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_PAIEMENTS_RESERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_PAIEMENTS_RESERVATION" ON "FOODLOOP"."PAIEMENTS" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_ROLES_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_ROLES_CODE" ON "FOODLOOP"."ROLES" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_ROLES_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_ROLES_NOM" ON "FOODLOOP"."ROLES" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_UTILISATEURS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_UTILISATEURS_EMAIL" ON "FOODLOOP"."UTILISATEURS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_RECUS_PAIEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOODLOOP"."UQ_RECUS_PAIEMENT" ON "FOODLOOP"."RECUS" ("PAIEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD PRIMARY KEY ("ID_NOTIFICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTIFICATIONS_RECIPIENT" CHECK (
        ((utilisateur_id IS NOT NULL) AND (admin_association_id IS NULL) AND (proprietaire_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NOT NULL) AND (proprietaire_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NULL) AND (proprietaire_id IS NOT NULL))
    ) ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTIFICATIONS_STATUS" CHECK (status IN ('queued', 'read', 'failed')) ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTIFICATIONS_CHANNEL" CHECK (channel IN ('sms', 'web', 'email')) ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "CHK_NOTIFICATIONS_TYPE" CHECK (type IN ('pickup_reminder', 'new_listing', 'expiration_alert', 'reservation_update', 'report_ready')) ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" MODIFY ("CHANNEL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" MODIFY ("MESSAGE_NOTIFICATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEUR_ZONES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEUR_ZONES" ADD PRIMARY KEY ("UTILISATEUR_ID", "ZONE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEUR_ZONES" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEUR_ZONES" MODIFY ("UTILISATEUR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSOCIATION_ADDRESSES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" ADD CONSTRAINT "CHK_ASSOC_PRIMARY" CHECK (is_primary IN (0, 1)) ENABLE;
  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" MODIFY ("IS_PRIMARY" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEUR_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" ADD PRIMARY KEY ("UTILISATEUR_ID", "CATEGORIE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" MODIFY ("CATEGORIE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" MODIFY ("UTILISATEUR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ROLES" ADD CONSTRAINT "UQ_ROLES_CODE" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ROLES" ADD CONSTRAINT "UQ_ROLES_NOM" UNIQUE ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ROLES" ADD PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ROLES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ROLES" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORGANIZATIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ORGANIZATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ORGANIZATIONS" MODIFY ("ORGANIZATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ORGANIZATIONS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSULTATIONS_ANNONCES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" ADD PRIMARY KEY ("ID_CONSULTATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" MODIFY ("DATE_CONSULTATION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" MODIFY ("ANNONCE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" MODIFY ("UTILISATEUR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUGGESTIONS_IA
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" ADD CONSTRAINT "CHK_AI" CHECK (risk_level IN ('low', 'medium', 'high')) ENABLE;
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" MODIFY ("GEN_AT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" MODIFY ("EXP_PROB" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" MODIFY ("RISK_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" MODIFY ("FOOD_ITEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEURS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEURS" ADD CONSTRAINT "UQ_UTILISATEURS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEURS" ADD PRIMARY KEY ("ID_UTIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("MOT_DE_PASSE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."UTILISATEURS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAIEMENTS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."PAIEMENTS" ADD CONSTRAINT "UQ_PAIEMENTS_RESERVATION" UNIQUE ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."PAIEMENTS" ADD PRIMARY KEY ("ID_PAIEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."PAIEMENTS" ADD CONSTRAINT "CHK_PAIEMENTS_STATUT" CHECK (statut IN ('confirme', 'annule')) ENABLE;
  ALTER TABLE "FOODLOOP"."PAIEMENTS" ADD CONSTRAINT "CHK_PAIEMENTS_METHODE" CHECK (methode_paiement IN ('par carte', 'espece')) ENABLE;
  ALTER TABLE "FOODLOOP"."PAIEMENTS" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PAIEMENTS" MODIFY ("DATE_PAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PAIEMENTS" MODIFY ("METHODE_PAIEMENT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PAIEMENTS" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PAIEMENTS" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTACT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."CONTACT_MESSAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."CONTACT_MESSAGES" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."CONTACT_MESSAGES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."CONTACT_MESSAGES" MODIFY ("FULLNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINS_ASSOCIATION
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ADMINS_ASSOCIATION" ADD PRIMARY KEY ("ID_ADMIN_ASSOCIATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ADMINS_ASSOCIATION" MODIFY ("NOM_ASSOCIATION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ADMINS_ASSOCIATION" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPER_ADMINS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."SUPER_ADMINS" ADD PRIMARY KEY ("ID_SUPER_ADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."SUPER_ADMINS" MODIFY ("MOT_DE_PASSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORT_CONSULTATIONS_COMMERCE
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" MODIFY ("CONSULTED_AT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" MODIFY ("PROPRIETAIRE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" MODIFY ("REPORT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PICKUPS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."PICKUPS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."PICKUPS" ADD CONSTRAINT "CHK_PICKUPS_STATUS" CHECK (status IN ('scheduled', 'in_progress', 'done', 'missed')) ENABLE;
  ALTER TABLE "FOODLOOP"."PICKUPS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PICKUPS" MODIFY ("SCHEDULED_AT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PICKUPS" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROPRIETAIRES_COMMERCE
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."PROPRIETAIRES_COMMERCE" ADD PRIMARY KEY ("ID_COMMERCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."PROPRIETAIRES_COMMERCE" MODIFY ("TYPE_COMMERCE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."PROPRIETAIRES_COMMERCE" MODIFY ("NOM_COMMERCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISTRIBUTIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" ADD PRIMARY KEY ("ID_DISTRIBUTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" ADD CONSTRAINT "CHK_DISTRIBUTIONS_STATUT" CHECK (statut IN ('planned', 'in_progress', 'completed', 'cancelled')) ENABLE;
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" MODIFY ("DATE_DISTRIB" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" MODIFY ("QUANTITE_DISTRIB" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" MODIFY ("ADMIN_ASSOCIATION_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESSES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ADDRESSES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ADDRESSES" MODIFY ("GOUVERNORAT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ADDRESSES" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ADDRESSES" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ADDRESSES" MODIFY ("STREET_LINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZONES_GEOGRAPHIQUES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" ADD PRIMARY KEY ("ID_ZONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" MODIFY ("GOUVERNORAT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" MODIFY ("VILLE_NOM" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" MODIFY ("CODE_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANNONCES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ANNONCES" ADD PRIMARY KEY ("ID_ANNONCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."ANNONCES" ADD CONSTRAINT "CHK_ANNONCES_STATUT" CHECK (statut IN ('available', 'reserved', 'priority_access', 'picked_up', 'expired', 'cancelled')) ENABLE;
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("PROPRIETAIRE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("ZONE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("CATEGORIE_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("DATE_EXPIRATION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("PICKUP_END" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("PICKUP_START" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("PUBLIC_VISIBILITY_AT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("LOCALISATION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("UNITE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("TYPE_ALIMENT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."ANNONCES" MODIFY ("TITRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."REPORTS" ADD CONSTRAINT "CHK_REPORTS_TYPE" CHECK (report_type IN ('daily', 'weekly', 'monthly', 'impact', 'custom')) ENABLE;
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("TOTAL_DISTRIBUTIONS" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("TOTAL_RESERVATIONS" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("TOTAL_FOOD_SAVED_KG" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("PERIOD_END" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("PERIOD_START" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("REPORT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORTS" MODIFY ("GENERATED_BY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION_DISTRIBUTIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" ADD PRIMARY KEY ("RESERVATION_ID", "DISTRIBUTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" MODIFY ("DISTRIBUTION_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECUS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RECUS" ADD CONSTRAINT "UQ_RECUS_PAIEMENT" UNIQUE ("PAIEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."RECUS" ADD PRIMARY KEY ("ID_RECU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."RECUS" MODIFY ("DATE_EMISSION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RECUS" MODIFY ("MONTANT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RECUS" MODIFY ("PAIEMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD PRIMARY KEY ("ID_RESERVATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD CONSTRAINT "CHK_RESERVATIONS_DEMANDEUR" CHECK (
        ((utilisateur_id IS NOT NULL) AND (admin_association_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NOT NULL))
    ) ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD CONSTRAINT "CHK_RESERVATIONS_STATUT" CHECK (statut IN ('pending', 'approved', 'rejected', 'picked_up', 'completed', 'cancelled')) ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATIONS" MODIFY ("DATE_PICKUP" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RESERVATIONS" MODIFY ("DATE_RESERVATION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RESERVATIONS" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RESERVATIONS" MODIFY ("QUANTITE_RESERVEE" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."RESERVATIONS" MODIFY ("ANNONCE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."CATEGORIES" ADD CONSTRAINT "UQ_CATEGORIES_NOM" UNIQUE ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."CATEGORIES" ADD PRIMARY KEY ("ID_CAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."CATEGORIES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."CATEGORIES" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORT_CONSULT_SUPER_ADMIN
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" MODIFY ("CONSULTED_AT" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" MODIFY ("SUPER_ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" MODIFY ("REPORT_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table ADMINS_ASSOCIATION
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ADMINS_ASSOCIATION" ADD CONSTRAINT "FK_ADMIN_ORG" FOREIGN KEY ("ORGANIZATION_ID")
	  REFERENCES "FOODLOOP"."ORGANIZATIONS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANNONCES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ANNONCES" ADD CONSTRAINT "FK_ANNONCES_CATEGORIE" FOREIGN KEY ("CATEGORIE_ID")
	  REFERENCES "FOODLOOP"."CATEGORIES" ("ID_CAT") ENABLE;
  ALTER TABLE "FOODLOOP"."ANNONCES" ADD CONSTRAINT "FK_ANNONCES_PROPRIETAIRE" FOREIGN KEY ("PROPRIETAIRE_ID")
	  REFERENCES "FOODLOOP"."PROPRIETAIRES_COMMERCE" ("ID_COMMERCE") ENABLE;
  ALTER TABLE "FOODLOOP"."ANNONCES" ADD CONSTRAINT "FK_ANNONCES_ZONE" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "FOODLOOP"."ZONES_GEOGRAPHIQUES" ("ID_ZONE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASSOCIATION_ADDRESSES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" ADD CONSTRAINT "FK_ASSOC_ADDR" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "FOODLOOP"."ADDRESSES" ("ID") ENABLE;
  ALTER TABLE "FOODLOOP"."ASSOCIATION_ADDRESSES" ADD CONSTRAINT "FK_ASSOC_ORG" FOREIGN KEY ("ORGANIZATION_ID")
	  REFERENCES "FOODLOOP"."ORGANIZATIONS" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CONSULTATIONS_ANNONCES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" ADD CONSTRAINT "FK_CONSULTATIONS_ANNONCE" FOREIGN KEY ("ANNONCE_ID")
	  REFERENCES "FOODLOOP"."ANNONCES" ("ID_ANNONCE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."CONSULTATIONS_ANNONCES" ADD CONSTRAINT "FK_CONSULTATIONS_USER" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table DISTRIBUTIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" ADD CONSTRAINT "FK_DISTRIBUTIONS_ASSOCIATION" FOREIGN KEY ("ADMIN_ASSOCIATION_ID")
	  REFERENCES "FOODLOOP"."ADMINS_ASSOCIATION" ("ID_ADMIN_ASSOCIATION") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."DISTRIBUTIONS" ADD CONSTRAINT "FK_DISTRIBUTIONS_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "FOODLOOP"."RESERVATIONS" ("ID_RESERVATION") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_ANNONCE" FOREIGN KEY ("ANNONCE_ID")
	  REFERENCES "FOODLOOP"."ANNONCES" ("ID_ANNONCE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_ASSOCIATION" FOREIGN KEY ("ADMIN_ASSOCIATION_ID")
	  REFERENCES "FOODLOOP"."ADMINS_ASSOCIATION" ("ID_ADMIN_ASSOCIATION") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_COMMERCE" FOREIGN KEY ("PROPRIETAIRE_ID")
	  REFERENCES "FOODLOOP"."PROPRIETAIRES_COMMERCE" ("ID_COMMERCE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_REPORT" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "FOODLOOP"."REPORTS" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "FOODLOOP"."RESERVATIONS" ("ID_RESERVATION") ON DELETE SET NULL ENABLE;
  ALTER TABLE "FOODLOOP"."NOTIFICATIONS" ADD CONSTRAINT "FK_NOTIFICATIONS_USER" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PAIEMENTS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."PAIEMENTS" ADD CONSTRAINT "FK_PAIEMENTS_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "FOODLOOP"."RESERVATIONS" ("ID_RESERVATION") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PICKUPS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."PICKUPS" ADD CONSTRAINT "FK_PICKUPS_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "FOODLOOP"."RESERVATIONS" ("ID_RESERVATION") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table RECUS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RECUS" ADD CONSTRAINT "FK_RECUS_PAIEMENT" FOREIGN KEY ("PAIEMENT_ID")
	  REFERENCES "FOODLOOP"."PAIEMENTS" ("ID_PAIEMENT") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT_CONSULTATIONS_COMMERCE
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" ADD CONSTRAINT "FK_RCC_OWN" FOREIGN KEY ("PROPRIETAIRE_ID")
	  REFERENCES "FOODLOOP"."PROPRIETAIRES_COMMERCE" ("ID_COMMERCE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."REPORT_CONSULTATIONS_COMMERCE" ADD CONSTRAINT "FK_RCC_REP" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "FOODLOOP"."REPORTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT_CONSULT_SUPER_ADMIN
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" ADD CONSTRAINT "FK_RCSA_REP" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "FOODLOOP"."REPORTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."REPORT_CONSULT_SUPER_ADMIN" ADD CONSTRAINT "FK_RCSA_SA" FOREIGN KEY ("SUPER_ADMIN_ID")
	  REFERENCES "FOODLOOP"."SUPER_ADMINS" ("ID_SUPER_ADMIN") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."REPORTS" ADD CONSTRAINT "FK_REPORTS_GENERATED_BY" FOREIGN KEY ("GENERATED_BY")
	  REFERENCES "FOODLOOP"."SUPER_ADMINS" ("ID_SUPER_ADMIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION_DISTRIBUTIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" ADD CONSTRAINT "FK_RD_DIST" FOREIGN KEY ("DISTRIBUTION_ID")
	  REFERENCES "FOODLOOP"."DISTRIBUTIONS" ("ID_DISTRIBUTION") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATION_DISTRIBUTIONS" ADD CONSTRAINT "FK_RD_RES" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "FOODLOOP"."RESERVATIONS" ("ID_RESERVATION") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATIONS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD CONSTRAINT "FK_RESERVATIONS_ANNONCE" FOREIGN KEY ("ANNONCE_ID")
	  REFERENCES "FOODLOOP"."ANNONCES" ("ID_ANNONCE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD CONSTRAINT "FK_RESERVATIONS_ASSOCIATION" FOREIGN KEY ("ADMIN_ASSOCIATION_ID")
	  REFERENCES "FOODLOOP"."ADMINS_ASSOCIATION" ("ID_ADMIN_ASSOCIATION") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."RESERVATIONS" ADD CONSTRAINT "FK_RESERVATIONS_USER" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ON DELETE CASCADE ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SUGGESTIONS_IA
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."SUGGESTIONS_IA" ADD CONSTRAINT "FK_AI" FOREIGN KEY ("FOOD_ITEM_ID")
	  REFERENCES "FOODLOOP"."ANNONCES" ("ID_ANNONCE") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table UTILISATEUR_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" ADD CONSTRAINT "FK_UC_CAT" FOREIGN KEY ("CATEGORIE_ID")
	  REFERENCES "FOODLOOP"."CATEGORIES" ("ID_CAT") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEUR_CATEGORIES" ADD CONSTRAINT "FK_UC_USER" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATEURS
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEURS" ADD CONSTRAINT "FK_UTILISATEURS_ROLE" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "FOODLOOP"."ROLES" ("ID_ROLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISATEUR_ZONES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."UTILISATEUR_ZONES" ADD CONSTRAINT "FK_UTILISATEUR_ZONES_USER" FOREIGN KEY ("UTILISATEUR_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FOODLOOP"."UTILISATEUR_ZONES" ADD CONSTRAINT "FK_UTILISATEUR_ZONES_ZONE" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "FOODLOOP"."ZONES_GEOGRAPHIQUES" ("ID_ZONE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZONES_GEOGRAPHIQUES
--------------------------------------------------------

  ALTER TABLE "FOODLOOP"."ZONES_GEOGRAPHIQUES" ADD CONSTRAINT "FK_ZONES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "FOODLOOP"."UTILISATEURS" ("ID_UTIL") ENABLE;
