CREATE TABLE roles (
    id_role NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    code VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_roles_nom UNIQUE (nom),
    CONSTRAINT uq_roles_code UNIQUE (code)
);

CREATE TABLE categories (
    id_cat NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    description CLOB NOT NULL,
    CONSTRAINT uq_categories_nom UNIQUE (nom)
);

CREATE TABLE utilisateurs (
    id_util NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER(19) NOT NULL,
    prenom VARCHAR2(120) NOT NULL,
    nom VARCHAR2(120) NOT NULL,
    email VARCHAR2(190) NOT NULL,
    mot_de_passe VARCHAR2(255) NOT NULL,
    num_tel VARCHAR2(30) NOT NULL,
    adresse VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_utilisateurs_role FOREIGN KEY (role_id) REFERENCES roles(id_role),
    CONSTRAINT uq_utilisateurs_email UNIQUE (email)
);

CREATE TABLE zones_geographiques (
    id_zone NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    code_postal NUMBER(10) NOT NULL,
    ville_nom VARCHAR2(120) NOT NULL,
    gouvernorat VARCHAR2(120) NOT NULL,
    user_id NUMBER(19) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_zones_user FOREIGN KEY (user_id) REFERENCES utilisateurs(id_util)
);

CREATE TABLE organizations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(180) NOT NULL,
    organization_type VARCHAR2(100) DEFAULT 'association' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE addresses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR2(120) NULL,
    street_line VARCHAR2(255) NOT NULL,
    city VARCHAR2(120) NOT NULL,
    postal_code VARCHAR2(20) NOT NULL,
    gouvernorat VARCHAR2(120) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE association_addresses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER(19) NOT NULL,
    address_id NUMBER(19) NOT NULL,
    is_primary NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_org_addresses_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_org_addresses_address FOREIGN KEY (address_id) REFERENCES addresses(id),
    CONSTRAINT chk_association_addresses_primary CHECK (is_primary IN (0, 1))
);

CREATE TABLE admins_association (
    id_admin_association NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id NUMBER(19) NOT NULL,
    nom_association VARCHAR2(180) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admins_association_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE proprietaires_commerce (
    id_commerce NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_commerce VARCHAR2(120) NOT NULL,
    type_commerce VARCHAR2(120) NOT NULL,
    business_licence VARCHAR2(120) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE super_admins (
    id_super_admin NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mot_de_passe VARCHAR2(255) NOT NULL,
    admin_level VARCHAR2(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE annonces (
    id_annonce NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR2(180) NOT NULL,
    description CLOB NULL,
    type_aliment VARCHAR2(120) NOT NULL,
    quantite NUMBER(10) NOT NULL,
    unite VARCHAR2(50) NOT NULL,
    localisation VARCHAR2(190) NOT NULL,
    statut VARCHAR2(30) NOT NULL,
    public_visibility_at TIMESTAMP NOT NULL,
    pickup_start TIMESTAMP NOT NULL,
    pickup_end TIMESTAMP NOT NULL,
    date_expiration TIMESTAMP NOT NULL,
    categorie_id NUMBER(19) NOT NULL,
    zone_id NUMBER(19) NOT NULL,
    proprietaire_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_annonces_categorie FOREIGN KEY (categorie_id) REFERENCES categories(id_cat),
    CONSTRAINT fk_annonces_zone FOREIGN KEY (zone_id) REFERENCES zones_geographiques(id_zone),
    CONSTRAINT fk_annonces_proprietaire FOREIGN KEY (proprietaire_id) REFERENCES proprietaires_commerce(id_commerce),
    CONSTRAINT chk_annonces_statut CHECK (statut IN ('available', 'reserved', 'priority_access', 'picked_up', 'expired', 'cancelled'))
);

CREATE TABLE utilisateur_categories (
    utilisateur_id NUMBER(19) NOT NULL,
    categorie_id NUMBER(19) NOT NULL,
    PRIMARY KEY (utilisateur_id, categorie_id),
    CONSTRAINT fk_utilisateur_categories_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id_util) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateur_categories_categorie FOREIGN KEY (categorie_id) REFERENCES categories(id_cat) ON DELETE CASCADE
);

CREATE TABLE utilisateur_zones (
    utilisateur_id NUMBER(19) NOT NULL,
    zone_id NUMBER(19) NOT NULL,
    PRIMARY KEY (utilisateur_id, zone_id),
    CONSTRAINT fk_utilisateur_zones_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id_util) ON DELETE CASCADE,
    CONSTRAINT fk_utilisateur_zones_zone FOREIGN KEY (zone_id) REFERENCES zones_geographiques(id_zone) ON DELETE CASCADE
);

CREATE TABLE consultations_annonces (
    id_consultation NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id NUMBER(19) NOT NULL,
    annonce_id NUMBER(19) NOT NULL,
    date_consultation TIMESTAMP NOT NULL,
    CONSTRAINT fk_consultations_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id_util) ON DELETE CASCADE,
    CONSTRAINT fk_consultations_annonce FOREIGN KEY (annonce_id) REFERENCES annonces(id_annonce) ON DELETE CASCADE
);

CREATE TABLE suggestions_ia (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_item_id NUMBER(19) NOT NULL,
    risk_level VARCHAR2(20) NOT NULL,
    exp_prob NUMBER(5, 2) NOT NULL,
    action CLOB NOT NULL,
    gen_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_predictions_food FOREIGN KEY (food_item_id) REFERENCES annonces(id_annonce),
    CONSTRAINT chk_suggestions_ia_risk CHECK (risk_level IN ('low', 'medium', 'high'))
);

CREATE TABLE reservations (
    id_reservation NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annonce_id NUMBER(19) NOT NULL,
    utilisateur_id NUMBER(19) NULL,
    admin_association_id NUMBER(19) NULL,
    quantite_reservee NUMBER(10) NOT NULL,
    statut VARCHAR2(30) NOT NULL,
    date_reservation TIMESTAMP NOT NULL,
    date_pickup TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reservations_annonce FOREIGN KEY (annonce_id) REFERENCES annonces(id_annonce) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id_util) ON DELETE CASCADE,
    CONSTRAINT fk_reservations_association FOREIGN KEY (admin_association_id) REFERENCES admins_association(id_admin_association) ON DELETE CASCADE,
    CONSTRAINT chk_reservations_statut CHECK (statut IN ('pending', 'approved', 'rejected', 'picked_up', 'completed', 'cancelled')),
    CONSTRAINT chk_reservations_demandeur CHECK (
        ((utilisateur_id IS NOT NULL) AND (admin_association_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NOT NULL))
    )
);

CREATE TABLE paiements (
    id_paiement NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER(19) NOT NULL,
    montant NUMBER(10, 2) NOT NULL,
    methode_paiement VARCHAR2(20) NOT NULL,
    date_paiement TIMESTAMP NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paiements_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id_reservation) ON DELETE CASCADE,
    CONSTRAINT uq_paiements_reservation UNIQUE (reservation_id),
    CONSTRAINT chk_paiements_methode CHECK (methode_paiement IN ('par carte', 'espece')),
    CONSTRAINT chk_paiements_statut CHECK (statut IN ('confirme', 'annule'))
);

CREATE TABLE recus (
    id_recu NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paiement_id NUMBER(19) NOT NULL,
    montant NUMBER(10, 2) NOT NULL,
    date_emission TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recus_paiement FOREIGN KEY (paiement_id) REFERENCES paiements(id_paiement) ON DELETE CASCADE,
    CONSTRAINT uq_recus_paiement UNIQUE (paiement_id)
);

CREATE TABLE pickups (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER(19) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    picked_up_at TIMESTAMP NULL,
    receiver_name VARCHAR2(150) NULL,
    receiver_phone VARCHAR2(30) NULL,
    pickup_code VARCHAR2(50) NULL,
    status VARCHAR2(20) DEFAULT 'scheduled' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pickups_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id_reservation),
    CONSTRAINT chk_pickups_status CHECK (status IN ('scheduled', 'in_progress', 'done', 'missed'))
);

CREATE TABLE distributions (
    id_distribution NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER(19) NOT NULL,
    admin_association_id NUMBER(19) NOT NULL,
    quantite_distrib NUMBER(10) NOT NULL,
    date_distrib TIMESTAMP NOT NULL,
    statut VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_distributions_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id_reservation) ON DELETE CASCADE,
    CONSTRAINT fk_distributions_association FOREIGN KEY (admin_association_id) REFERENCES admins_association(id_admin_association) ON DELETE CASCADE,
    CONSTRAINT chk_distributions_statut CHECK (statut IN ('planned', 'in_progress', 'completed', 'cancelled'))
);

CREATE TABLE reservation_distributions (
    reservation_id NUMBER(19) NOT NULL,
    distribution_id NUMBER(19) NOT NULL,
    PRIMARY KEY (reservation_id, distribution_id),
    CONSTRAINT fk_reservation_distributions_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id_reservation) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_distributions_distribution FOREIGN KEY (distribution_id) REFERENCES distributions(id_distribution) ON DELETE CASCADE
);

CREATE TABLE reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generated_by NUMBER(19) NOT NULL,
    report_type VARCHAR2(20) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_food_saved_kg NUMBER(12, 2) DEFAULT 0 NOT NULL,
    total_reservations NUMBER(10) DEFAULT 0 NOT NULL,
    total_distributions NUMBER(10) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_generated_by FOREIGN KEY (generated_by) REFERENCES super_admins(id_super_admin),
    CONSTRAINT chk_reports_type CHECK (report_type IN ('daily', 'weekly', 'monthly', 'impact', 'custom'))
);

CREATE TABLE report_consultations_commerce (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER(19) NOT NULL,
    proprietaire_id NUMBER(19) NOT NULL,
    consulted_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_consultations_commerce_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_consultations_commerce_owner FOREIGN KEY (proprietaire_id) REFERENCES proprietaires_commerce(id_commerce) ON DELETE CASCADE
);

CREATE TABLE report_consult_super_admin (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id NUMBER(19) NOT NULL,
    super_admin_id NUMBER(19) NOT NULL,
    consulted_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_consultations_super_admin_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_consultations_super_admin_admin FOREIGN KEY (super_admin_id) REFERENCES super_admins(id_super_admin) ON DELETE CASCADE
);

CREATE TABLE notifications (
    id_notification NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id NUMBER(19) NULL,
    admin_association_id NUMBER(19) NULL,
    proprietaire_id NUMBER(19) NULL,
    annonce_id NUMBER(19) NULL,
    reservation_id NUMBER(19) NULL,
    report_id NUMBER(19) NULL,
    message_notification CLOB NOT NULL,
    type VARCHAR2(30) NOT NULL,
    channel VARCHAR2(10) NOT NULL,
    sent_at TIMESTAMP NULL,
    read_at TIMESTAMP NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs(id_util) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_association FOREIGN KEY (admin_association_id) REFERENCES admins_association(id_admin_association) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_commerce FOREIGN KEY (proprietaire_id) REFERENCES proprietaires_commerce(id_commerce) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_annonce FOREIGN KEY (annonce_id) REFERENCES annonces(id_annonce) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id_reservation) ON DELETE SET NULL,
    CONSTRAINT fk_notifications_report FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE SET NULL,
    CONSTRAINT chk_notifications_type CHECK (type IN ('pickup_reminder', 'new_listing', 'expiration_alert', 'reservation_update', 'report_ready')),
    CONSTRAINT chk_notifications_channel CHECK (channel IN ('sms', 'web', 'email')),
    CONSTRAINT chk_notifications_status CHECK (status IN ('queued', 'read', 'failed')),
    CONSTRAINT chk_notifications_recipient CHECK (
        ((utilisateur_id IS NOT NULL) AND (admin_association_id IS NULL) AND (proprietaire_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NOT NULL) AND (proprietaire_id IS NULL))
        OR
        ((utilisateur_id IS NULL) AND (admin_association_id IS NULL) AND (proprietaire_id IS NOT NULL))
    )
);

CREATE TABLE contact_messages (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR2(180) NOT NULL,
    email VARCHAR2(190) NOT NULL,
    organization VARCHAR2(180) NULL,
    role_label VARCHAR2(100) NULL,
    message CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_annonces_visibility ON annonces(public_visibility_at, statut);
CREATE INDEX idx_reservations_status ON reservations(statut);
CREATE INDEX idx_notifications_status ON notifications(status, type);
CREATE INDEX idx_pickups_status ON pickups(status);
CREATE INDEX idx_reports_type ON reports(report_type);
