CREATE TABLE ACCOUNT_MODERATION (
    ID NUMBER(19,0) PRIMARY KEY,
    UTILISATEUR_ID NUMBER(19,0) NOT NULL,
    STATUS VARCHAR2(20 BYTE) DEFAULT 'active' NOT NULL,
    REASON VARCHAR2(255 BYTE),
    CREATED_AT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_ACCOUNT_MODERATION_USER UNIQUE (UTILISATEUR_ID),
    CONSTRAINT CHK_ACCOUNT_MODERATION_STATUS CHECK (STATUS IN ('active', 'suspended')),
    CONSTRAINT FK_ACCOUNT_MODERATION_USER FOREIGN KEY (UTILISATEUR_ID)
        REFERENCES UTILISATEURS (ID_UTIL) ON DELETE CASCADE
);
