WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'ANNONCES'
      AND COLUMN_NAME = 'PRIX';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ANNONCES ADD (PRIX NUMBER(10,2) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

UPDATE ANNONCES SET PRIX = 2.90 WHERE ID_ANNONCE = 1 AND NVL(PRIX, 0) = 0;
UPDATE ANNONCES SET PRIX = 4.60 WHERE ID_ANNONCE = 2 AND NVL(PRIX, 0) = 0;
UPDATE ANNONCES SET PRIX = 3.40 WHERE ID_ANNONCE = 3 AND NVL(PRIX, 0) = 0;
UPDATE ANNONCES SET PRIX = 2.30 WHERE ID_ANNONCE = 4 AND NVL(PRIX, 0) = 0;
UPDATE ANNONCES SET PRIX = 1.80 WHERE ID_ANNONCE = 5 AND NVL(PRIX, 0) = 0;

COMMIT;
EXIT;
